### ISSUE TITLE
sd for qe.mean.sd by S2 does not change with n

### ISSUE THREAD

**Issue by wnarifin** [stmcg/estmeansd#4]
Hi, thank you for the R package.

As for qe.mean.sd() function, I noted when using information for S2 (Q1, Q3, median, n), the resulting sd remains constant with different n. Is this an expected behavior? I include the code and results below. It worked well for S1 and S3. R version 4.4.1 with estmeansd version 1.0.1.

sd does not change with n
```
> # S2
> estmeansd::qe.mean.sd(q1.val = 100, q3.val = 140, 
+                       med.val = 120, n = 1000)
$est.mean
[1] 120

$est.sd
[1] 29.65204
> estmeansd::qe.mean.sd(q1.val = 100, q3.val = 140, 
+                       med.val = 120, n = 10)
$est.mean
[1] 120

$est.sd
[1] 29.65204
```

sd changes with n S1 and S3
```
> # S1
> estmeansd::qe.mean.sd(min.val = 90, max.val = 150,
+                       q1.val = 100, q3.val = 140, 
+                       med.val = 120, n = 1000)
$est.mean
[1] 120

$est.sd
[1] 10.61493
> estmeansd::qe.mean.sd(min.val = 90, max.val = 150,
+                       q1.val = 100, q3.val = 140, 
+                       med.val = 120, n = 10)
$est.mean
[1] 120

$est.sd
[1] 24.7633

> # S3
> estmeansd::qe.mean.sd(min.val = 90, max.val = 150,
+                       med.val = 120, n = 1000)
$est.mean
[1] 120

$est.sd
[1] 9.708008
> estmeansd::qe.mean.sd(min.val = 90, max.val = 150,
+                       med.val = 120, n = 10)
$est.mean
[1] 120

$est.sd
[1] 23.40912
```

**Comment by stmcg** [comment]
Hi, thanks for posting the question. 

Yes, I think this behavior makes sense. To recap, the QE method estimates the mean and standard deviation by essentially equating the sample quantiles to the distribution quantiles. For S1 and S3, the sample quantiles involve the minimum (ie, 1/n quantile) and the maximum (ie, 1-1/n) quantiles which depend on n. For S2, the sample quantiles are just the 0.25, 0.5, and 0.75 quantiles, which don't depend on n. So I wouldn't expect the estimation procedure to depend on n. 

And heads up that this function is estimating the _standard deviation_ rather than the _standard error_ (which would indeed get smaller as n gets larger). The standard error of the QE method (needed in meta-analysis, for example) can be obtained by the `get_SE` function

Does this clarify?

**Comment by wnarifin** [comment]
Thank you for the clarification. I was comparing your results with that of Wan et al. (2014), so I wondered why they differed. After you clarified the approach used in your method, now that makes sense.

Thanks again.
